"""add serial_num and description attributes to device

Revision ID: 7349560fa8e9
Revises: 29fe0a868f5f
Create Date: 2022-06-17 04:37:11.341597

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "7349560fa8e9"
down_revision = "29fe0a868f5f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "device",
        sa.Column("serial_num", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.add_column(
        "device",
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    #op.alter_column("device", "id", existing_type=postgresql.UUID(), nullable=True)
    #op.alter_column("invoice", "id", existing_type=postgresql.UUID(), nullable=True)
    #op.alter_column("user", "id", existing_type=postgresql.UUID(), nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("user", "id", existing_type=postgresql.UUID(), nullable=False)
    op.alter_column("invoice", "id", existing_type=postgresql.UUID(), nullable=False)
    op.alter_column("device", "id", existing_type=postgresql.UUID(), nullable=False)
    op.drop_column("device", "description")
    op.drop_column("device", "serial_num")
    # ### end Alembic commands ###
